import AppKit
import XCTest
@testable import TidyTapInputEngine

final class ClipboardPasteboardReaderTests: XCTestCase {
    func testCapturesRichTextAndPrefersImageDataOverAnImageURL() throws {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }

        let rich = NSPasteboardItem()
        let rtf = Data("{\\rtf1\\ansi\\b Bold\\b0}".utf8)
        XCTAssertTrue(rich.setString("Bold", forType: .string))
        XCTAssertTrue(rich.setData(rtf, forType: .rtf))
        XCTAssertTrue(board.writeObjects([rich]))
        XCTAssertEqual(
            ClipboardPasteboardReader.capture(from: board)?.content,
            .text(plain: "Bold", rtf: rtf, html: nil)
        )

        board.clearContents()
        let image = NSPasteboardItem()
        let png = try XCTUnwrap(Data(base64Encoded:
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aJX8AAAAASUVORK5CYII="))
        XCTAssertTrue(image.setString("https://example.test/image.png", forType: .string))
        XCTAssertTrue(image.setString("<img src=\"https://example.test/image.png\">", forType: .html))
        XCTAssertTrue(image.setData(png, forType: .png))
        XCTAssertTrue(board.writeObjects([image]))
        XCTAssertEqual(ClipboardPasteboardReader.capture(from: board)?.content, .image(data: png, type: .png))

        board.clearContents()
        let imageWithAlt = NSPasteboardItem()
        let imageHTML = Data("<a href=\"https://example.test\"><img alt=\"preview\" src=\"image.png\"></a>".utf8)
        XCTAssertTrue(imageWithAlt.setString("preview", forType: .string))
        XCTAssertTrue(imageWithAlt.setData(imageHTML, forType: .html))
        XCTAssertTrue(imageWithAlt.setData(png, forType: .png))
        XCTAssertTrue(board.writeObjects([imageWithAlt]))
        XCTAssertEqual(ClipboardPasteboardReader.capture(from: board)?.content, .image(data: png, type: .png))

        board.clearContents()
        let tiffItem = NSPasteboardItem()
        let tiff = Data([0x49, 0x49, 0x2A, 0x00])
        XCTAssertTrue(tiffItem.setData(tiff, forType: .tiff))
        XCTAssertTrue(board.writeObjects([tiffItem]))
        XCTAssertEqual(ClipboardPasteboardReader.capture(from: board)?.content, .image(data: tiff, type: .tiff))

        board.clearContents()
        let mixed = NSPasteboardItem()
        XCTAssertTrue(mixed.setString("A paragraph with an image", forType: .string))
        XCTAssertTrue(mixed.setData(rtf, forType: .rtf))
        XCTAssertTrue(mixed.setData(png, forType: .png))
        XCTAssertTrue(board.writeObjects([mixed]))
        XCTAssertEqual(
            ClipboardPasteboardReader.capture(from: board)?.content,
            .text(plain: "A paragraph with an image", rtf: rtf, html: nil)
        )

        board.clearContents()
        let mixedHTML = NSPasteboardItem()
        let markup = Data("<p>A paragraph</p><img src=\"image.png\">".utf8)
        XCTAssertTrue(mixedHTML.setString("A paragraph", forType: .string))
        XCTAssertTrue(mixedHTML.setData(markup, forType: .html))
        XCTAssertTrue(mixedHTML.setData(png, forType: .png))
        XCTAssertTrue(board.writeObjects([mixedHTML]))
        XCTAssertEqual(
            ClipboardPasteboardReader.capture(from: board)?.content,
            .text(plain: "A paragraph", rtf: nil, html: markup)
        )
    }

    func testExcludesCopiedFilesAndNonPersistentItems() {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }

        let file = NSPasteboardItem()
        XCTAssertTrue(file.setString("file:///tmp/image.png", forType: .fileURL))
        XCTAssertTrue(file.setString("image.png", forType: .string))
        XCTAssertTrue(board.writeObjects([file]))
        XCTAssertNil(ClipboardPasteboardReader.capture(from: board))

        for marker in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ] {
            board.clearContents()
            let marked = NSPasteboardItem()
            XCTAssertTrue(marked.setString("not for history", forType: .string))
            XCTAssertTrue(marked.setString("1", forType: NSPasteboard.PasteboardType(marker)))
            XCTAssertTrue(board.writeObjects([marked]))
            XCTAssertNil(ClipboardPasteboardReader.capture(from: board), marker)
        }

        board.clearContents()
        let first = NSPasteboardItem()
        let second = NSPasteboardItem()
        XCTAssertTrue(first.setString("ordinary item", forType: .string))
        XCTAssertTrue(second.setString("private item", forType: .string))
        XCTAssertTrue(second.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")))
        XCTAssertTrue(board.writeObjects([first, second]))
        XCTAssertNil(ClipboardPasteboardReader.capture(from: board), "a marked item excludes the whole copy")

        board.clearContents()
        let ordinary = NSPasteboardItem()
        XCTAssertTrue(ordinary.setString("keep", forType: .string))
        XCTAssertTrue(board.writeObjects([ordinary]))
        XCTAssertEqual(ClipboardPasteboardReader.capture(from: board)?.content,
                       .text(plain: "keep", rtf: nil, html: nil))
    }
}
