import AppKit
import XCTest
@testable import TidyTapInputEngine

@MainActor
final class ClipboardPasteboardWriterTests: XCTestCase {
    func testTextStyleControlsRepresentationsAndOwnPasteIsNotRecaptured() {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }
        let content = ClipboardCapturedContent.text(
            plain: "Bold", rtf: Data("rtf".utf8), html: Data("<b>Bold</b>".utf8)
        )

        XCTAssertTrue(ClipboardPasteboardWriter.write(content, style: .plain, to: board))
        XCTAssertEqual(board.string(forType: .string), "Bold")
        XCTAssertNil(board.data(forType: .rtf))
        XCTAssertNil(board.data(forType: .html))
        XCTAssertNil(ClipboardPasteboardReader.capture(from: board))

        XCTAssertTrue(ClipboardPasteboardWriter.write(content, style: .formatted, to: board))
        XCTAssertEqual(board.data(forType: .rtf), Data("rtf".utf8))
        XCTAssertEqual(board.data(forType: .html), Data("<b>Bold</b>".utf8))
        XCTAssertEqual(board.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")), "1")
        XCTAssertNil(ClipboardPasteboardReader.capture(from: board))
    }

    func testImageAlwaysRemainsAnImage() {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }
        let png = Data([0x89, 0x50, 0x4E, 0x47])
        XCTAssertTrue(ClipboardPasteboardWriter.write(.image(data: png, type: .png), style: .plain, to: board))
        XCTAssertEqual(board.data(forType: .png), png)
        XCTAssertNil(board.string(forType: .string))

        let tiff = Data([0x49, 0x49, 0x2A, 0x00])
        XCTAssertTrue(ClipboardPasteboardWriter.write(.image(data: tiff, type: .tiff), style: .formatted, to: board))
        XCTAssertEqual(board.data(forType: .tiff), tiff)
        XCTAssertNil(board.data(forType: .png))
    }

    func testNativeTextViewCanInsertFormattedTextAndImageFromWrittenRepresentations() throws {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }
        let original = NSAttributedString(
            string: "Bold text",
            attributes: [.font: NSFont.boldSystemFont(ofSize: 18)]
        )
        let rtf = try original.data(
            from: NSRange(location: 0, length: original.length),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]
        )
        XCTAssertTrue(ClipboardPasteboardWriter.write(
            .text(plain: original.string, rtf: rtf, html: nil), style: .formatted, to: board
        ))
        let textView = NSTextView(frame: NSRect(x: 0, y: 0, width: 300, height: 100))
        XCTAssertTrue(textView.readSelection(from: board, type: .rtf))
        XCTAssertEqual(textView.string, original.string)
        let pastedFont = try XCTUnwrap(textView.textStorage?.attribute(.font, at: 0, effectiveRange: nil) as? NSFont)
        XCTAssertTrue(pastedFont.fontDescriptor.symbolicTraits.contains(.bold))

        XCTAssertTrue(ClipboardPasteboardWriter.write(
            .text(plain: original.string, rtf: rtf, html: nil), style: .plain, to: board
        ))
        let plainView = NSTextView(frame: NSRect(x: 0, y: 0, width: 300, height: 100))
        XCTAssertTrue(plainView.readSelection(from: board, type: .string))
        XCTAssertEqual(plainView.string, original.string)
        let plainFont = plainView.textStorage?.attribute(.font, at: 0, effectiveRange: nil) as? NSFont
        XCTAssertFalse(plainFont?.fontDescriptor.symbolicTraits.contains(.bold) ?? false)

        let png = try XCTUnwrap(Data(base64Encoded:
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aJX8AAAAASUVORK5CYII="))
        XCTAssertTrue(ClipboardPasteboardWriter.write(.image(data: png, type: .png), style: .plain, to: board))
        let imageView = NSTextView(frame: NSRect(x: 0, y: 0, width: 300, height: 100))
        XCTAssertTrue(imageView.readSelection(from: board, type: .png))
        XCTAssertNotNil(imageView.textStorage?.attribute(.attachment, at: 0, effectiveRange: nil) as? NSTextAttachment)
    }
}
