import AppKit

public enum ClipboardImageType: String, Codable, Hashable {
    case png
    case tiff

    var pasteboardType: NSPasteboard.PasteboardType {
        switch self {
        case .png: .png
        case .tiff: .tiff
        }
    }
}

public enum ClipboardCapturedContent: Codable, Hashable {
    case text(plain: String, rtf: Data?, html: Data?)
    case image(data: Data, type: ClipboardImageType)
}

public struct ClipboardCapture: Equatable {
    public let changeCount: Int
    public let content: ClipboardCapturedContent
}

/// Reads one current copy from a supplied pasteboard. The caller decides when
/// to read and whether OS privacy state allows it; tests use a named board.
public enum ClipboardPasteboardReader {
    public static func capture(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let changeCount = pasteboard.changeCount
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return nil }

        let fileTypes: Set<NSPasteboard.PasteboardType> = [
            .fileURL, NSPasteboard.PasteboardType("NSFilenamesPboardType")
        ]
        let nonPersistentTypes: Set<NSPasteboard.PasteboardType> = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
            ClipboardPasteboardWriter.internalType
        ]
        guard !items.contains(where: { item in
            let types = Set(item.types)
            return !types.isDisjoint(with: fileTypes) || !types.isDisjoint(with: nonPersistentTypes)
        }) else { return nil }

        let plain = items.compactMap { $0.string(forType: .string) }.joined(separator: "\n")
        let rtf = items.count == 1 ? items[0].data(forType: .rtf) : nil
        let html = items.count == 1 ? items[0].data(forType: .html) : nil
        let image = items.lazy.compactMap { $0.data(forType: .png) }.first
            .map { ClipboardCapturedContent.image(data: $0, type: .png) }
            ?? items.lazy.compactMap { $0.data(forType: .tiff) }.first
                .map { ClipboardCapturedContent.image(data: $0, type: .tiff) }
        let webImageURL = URL(string: plain)?.scheme.map { ["http", "https"].contains($0.lowercased()) } == true
        let imageOnlyHTML: Bool = {
            guard image != nil, rtf == nil, !webImageURL,
                  let html, let markup = String(data: html, encoding: .utf8),
                  markup.range(of: "<img\\b", options: [.regularExpression, .caseInsensitive]) != nil else {
                return false
            }
            let text = markup.replacingOccurrences(of: "<[^>]*>", with: "", options: .regularExpression)
            return text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }()

        let content: ClipboardCapturedContent
        if let image, rtf == nil, (html == nil || webImageURL || imageOnlyHTML) {
            content = image
        } else if !plain.isEmpty, rtf != nil || html != nil {
            content = .text(plain: plain, rtf: rtf, html: html)
        } else if let image {
            content = image
        } else if !plain.isEmpty {
            content = .text(plain: plain, rtf: nil, html: nil)
        } else {
            return nil
        }
        guard pasteboard.changeCount == changeCount else { return nil }
        return ClipboardCapture(changeCount: changeCount, content: content)
    }
}
