import AppKit

public enum ClipboardTextPasteStyle {
    case plain
    case formatted
}

public enum ClipboardPasteboardWriter {
    public static let internalType = NSPasteboard.PasteboardType("com.sharknia.TidyTap.InternalPaste")

    @discardableResult
    public static func write(
        _ content: ClipboardCapturedContent,
        style: ClipboardTextPasteStyle,
        to pasteboard: NSPasteboard
    ) -> Bool {
        let item = NSPasteboardItem()
        switch content {
        case .text(let plain, let rtf, let html):
            guard item.setString(plain, forType: .string) else { return false }
            if style == .formatted {
                if let rtf { guard item.setData(rtf, forType: .rtf) else { return false } }
                if let html { guard item.setData(html, forType: .html) else { return false } }
            }
        case .image(let data, let type):
            guard item.setData(data, forType: type.pasteboardType) else { return false }
        }
        guard item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) else {
            return false
        }
        guard item.setString("1", forType: internalType) else { return false }
        pasteboard.clearContents()
        return pasteboard.writeObjects([item])
    }
}
